### ISSUE TITLE
Task ID is needed in testing?

### ISSUE THREAD

**Issue by Wang-Z-W** [sun-hailong/CVPR24-Ease#4]
Thank you for your splendid work. There is a claim in the paper that you reweight the logit. Is there a need of task ID of each sample during testing, and thus your experiment setting is task increment rather than class increment?

**Comment by sun-hailong** [comment]
Hi @Wang-Z-W,
you can see this similar issue here: https://github.com/sun-hailong/CVPR24-Ease/issues/3#issuecomment-2075398855

**Comment by Wang-Z-W** [comment]
> Hi @Wang-Z-W,
> you can see this similar issue here: https://github.com/sun-hailong/CVPR24-Ease/issues/3#issuecomment-2075398855

Thank you!

**Comment by zhoudw-zdw** [comment]
The reweight process does not rely on the task ID. It only changes the logit calculation process depending on whether the item belongs to the diagonal component. To understand this point, I suggest you review Eq. 10 to Eq. 12 in the main paper. 

Take a 2-task CIL for an example. The basic logit calculation for the first task classes is achieved by matching \phi_1(x) to P11 and matching phi_2(x) to P12 and aggregating them. Since P11 is the diagonal component while P12 is not, the reweighting process only adjusts the combination weight among them. 

It is clear that we do not utilize the task ID since deciding the diagonal component is irrelevant to it.

**Comment by lemoshu** [comment]
> The reweight process does not rely on the task ID. It only changes the logit calculation process depending on whether the item belongs to the diagonal component. To understand this point, I suggest you review Eq. 10 to Eq. 12 in the main paper.
> 
> Take a 2-task CIL for an example. The basic logit calculation for the first task classes is achieved by matching \phi_1(x) to P11 and matching phi_2(x) to P12 and aggregating them. Since P11 is the diagonal component while P12 is not, the reweighting process only adjusts the combination weight among them.
> 
> It is clear that we do not utilize the task ID since deciding the diagonal component is irrelevant to it.

I have a follow-up question: taking this 2-task CIL for example after the entire training, based on your clarification, given an image X originally from task 1, we still need to know that X belongs to task 1. Then, use the diagonal component P11 more. Is it the task id? Because if you do not give the task 1 (identity), the model cannot distinguish where the image X is from and may use P22 (also the diagonal).

**Comment by lemoshu** [comment]
> The reweight process does not rely on the task ID. It only changes the logit calculation process depending on whether the item belongs to the diagonal component. To understand this point, I suggest you review Eq. 10 to Eq. 12 in the main paper.
> 
> Take a 2-task CIL for an example. The basic logit calculation for the first task classes is achieved by matching \phi_1(x) to P11 and matching phi_2(x) to P12 and aggregating them. Since P11 is the diagonal component while P12 is not, the reweighting process only adjusts the combination weight among them.
> 
> It is clear that we do not utilize the task ID since deciding the diagonal component is irrelevant to it.

Like here, you know you are handling task 1 during inference, so you use P11 rather than P22.
